// Sitenin tüm içerik verisi. Firma bilgileri ve ürünler buradan düzenlenir.

export const SITE = {
  name: 'Akya Mantar',
  legalName: 'AKYA MANTAR DIŞ TİCARET A.Ş.',
  // TODO: Gerçek iletişim bilgileriyle değiştirin.
  phone: '+90 (000) 000 00 00',
  phoneHref: '+900000000000',
  email: 'info@akyamantar.com.tr',
  address: 'Adres bilgisi eklenecek, İlçe / İl, Türkiye',
  hours: 'Pazartesi – Cuma, 08:30 – 18:00',
  mapEmbed: '', // Google Maps "Haritayı yerleştir" iframe src adresi
};

export const NAV = [
  { href: 'index.html', label: 'Anasayfa', key: 'home' },
  { href: 'kurumsal.html', label: 'Kurumsal', key: 'kurumsal' },
  { href: 'urunler.html', label: 'Ürünler', key: 'urunler' },
  { href: 'iletisim.html', label: 'İletişim', key: 'iletisim' },
];

export const FORMS = {
  taze: 'Taze',
  kurutulmus: 'Kurutulmuş',
  dondurulmus: 'Dondurulmuş',
  salamura: 'Salamura',
};

export const MONTHS = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'];

// shape: illüstrasyon tipi (bolete | cap | funnel | trumpet | morel | truffle | spiny)
// season: hasat ayları (1–12)
export const PRODUCTS = [
  {
    slug: 'cam-mantari',
    name: 'Çam Mantarı',
    latin: 'Tricholoma anatolicum',
    trade: 'Anatolian Matsutake',
    otherNames: ['Anadolu Matsutakesi', 'Sedir mantarı'],
    shape: 'cap',
    color: '#C9B79C',
    season: [9, 10, 11],
    regions: ['Akdeniz', 'Toros Dağları', 'Göller Bölgesi'],
    forms: ['taze', 'dondurulmus'],
    summary: 'Toros sedir ve çam ormanlarının en değerli mantarı; yoğun, baharatlı aroması ile özellikle Uzak Doğu pazarında aranan bir tür.',
    description: [
      'Çam mantarı, Toros Dağları ve Akdeniz kuşağındaki yaşlı sedir ve kızılçam ormanlarında, toprağın hemen altında gelişir. Sonbahar yağmurlarıyla birlikte kısa bir dönemde toplanır.',
      'Sıkı dokulu beyaz eti ve kendine özgü baharatlı kokusu nedeniyle Japonya başta olmak üzere Uzak Doğu mutfaklarında matsutake olarak değerlendirilir. Ürün, toplandığı gün sınıflandırılarak soğuk zincirle sevk edilir.',
    ],
    features: [
      ['Şapka', '5–20 cm, kahverengi pullu, kenarları içe kıvrık'],
      ['Et', 'Beyaz, sıkı ve lifli'],
      ['Koku', 'Yoğun, baharatlı – tarçınımsı'],
      ['Sınıflandırma', 'Kapalı şapka / açık şapka, boy ve ağırlığa göre'],
    ],
    usage: 'Izgara, buharda pişirme, pilav ve et suyu çorbaları.',
  },
  {
    slug: 'ayi-mantari',
    name: 'Ayı Mantarı',
    latin: 'Boletus edulis',
    trade: 'Porcini / Cep',
    otherNames: ['Çörek mantarı', 'Kestane mantarı'],
    shape: 'bolete',
    color: '#8A4B2A',
    season: [6, 7, 8, 9, 10],
    regions: ['Karadeniz', 'Marmara', 'Batı Anadolu'],
    forms: ['taze', 'kurutulmus', 'dondurulmus'],
    summary: 'Avrupa mutfağının “porcini”si. Fındıksı aroması ve etli yapısı ile hem taze hem kurutulmuş olarak en çok ihraç edilen yabani mantarlardan biridir.',
    description: [
      'Ayı mantarı; kayın, meşe, kestane ve çam ormanlarında ağaç kökleriyle ortak yaşam kuran, şişkin saplı, kahverengi şapkalı bir türdür. Karadeniz ve Marmara ormanlarında yazdan sonbaharın ortasına kadar toplanır.',
      'Toplanan ürünler boy, sertlik ve kurt kontrolüne göre ayrılır. Taze olarak sevk edilmesinin yanı sıra dilimlenerek kurutulur veya bütün/küp olarak dondurulur.',
    ],
    features: [
      ['Şapka', '8–25 cm, açık-koyu kahverengi, yağlımsı yüzey'],
      ['Alt yüzey', 'Süngerimsi gözenekli; gençken beyaz, olgunlukta sarı-yeşil'],
      ['Sap', 'Kalın, şişkin, beyaz ağ desenli'],
      ['Sınıflandırma', 'Extra / I. sınıf / II. sınıf; bütün, dilim, küp'],
    ],
    usage: 'Risotto, makarna sosları, çorba, et yemekleri; kurusu toz ve et suyu olarak.',
  },
  {
    slug: 'sarikiz-mantari',
    name: 'Sarıkız Mantarı',
    latin: 'Cantharellus cibarius',
    trade: 'Chanterelle / Girolle',
    otherNames: ['Horoz mantarı', 'Yumurta mantarı'],
    shape: 'funnel',
    color: '#E9A925',
    season: [6, 7, 8, 9, 10, 11],
    regions: ['Karadeniz', 'Marmara', 'Ege'],
    forms: ['taze', 'dondurulmus', 'salamura'],
    summary: 'Yumurta sarısı rengi ve hafif kayısı kokusuyla tanınan, Avrupa pazarının en sevilen yabani mantarlarından biri.',
    description: [
      'Sarıkız mantarı nemli kayın, meşe ve kestane ormanlarında, yosunlu zeminlerde kümeler halinde yetişir. Huni biçimli şapkası ve sapa doğru inen kaba kıvrımlarıyla kolayca ayırt edilir.',
      'Dayanıklı yapısı sayesinde taze ihracata uygundur. Sezon dışı talepler için dondurulmuş ve salamura olarak da hazırlanır.',
    ],
    features: [
      ['Şapka', '3–10 cm, huni biçimli, dalgalı kenarlı'],
      ['Renk', 'Yumurta sarısı – turuncu'],
      ['Alt yüzey', 'Sapa inen kalın, çatallanan damarlar'],
      ['Koku', 'Hafif meyvemsi, kayısıyı andırır'],
    ],
    usage: 'Tereyağında sote, omlet, krema soslar, av etleri yanında.',
  },
  {
    slug: 'kuzugobegi-mantari',
    name: 'Kuzugöbeği Mantarı',
    latin: 'Morchella spp.',
    trade: 'Morel',
    otherNames: ['Kuzu mantarı', 'Kuzu kulağı'],
    shape: 'morel',
    color: '#9C7A55',
    season: [3, 4, 5],
    regions: ['Doğu Anadolu', 'İç Anadolu', 'Ege', 'Karadeniz'],
    forms: ['kurutulmus', 'taze'],
    summary: 'Bal peteği görünümlü şapkasıyla dünyanın en değerli yabani mantarlarından. Ağırlıklı olarak kurutulmuş formda ihraç edilir.',
    description: [
      'Kuzugöbeği, ilkbaharda kar sularının çekilmesiyle orman açıklıklarında, meyve bahçelerinde ve yanmış orman alanlarında ortaya çıkar. Sezonu kısa, toplanması emek yoğundur.',
      'Gölgede, kontrollü ortamda kurutulur; ardından boy ve renk gruplarına ayrılarak paketlenir. Kurutulmuş kuzugöbeği aromasını uzun süre korur.',
    ],
    features: [
      ['Şapka', 'Konik – oval, bal peteği gibi çukurlu'],
      ['Renk', 'Krem, kahverengi veya siyahımsı (türe göre)'],
      ['Yapı', 'Şapka ve sap içi boş'],
      ['Sınıflandırma', 'Boy (cm) ve renk; saplı / sapsız kesim'],
    ],
    usage: 'Krema soslar, dolma, et ve tavuk yemekleri; kurusu ılık suda bekletilerek.',
  },
  {
    slug: 'kanlica-mantari',
    name: 'Kanlıca Mantarı',
    latin: 'Lactarius deliciosus',
    trade: 'Saffron Milk Cap',
    otherNames: ['Çıntar', 'Melki', 'Çam melkisi'],
    shape: 'cap',
    color: '#E07A2E',
    season: [9, 10, 11, 12],
    regions: ['Marmara', 'Ege', 'Karadeniz', 'Akdeniz'],
    forms: ['taze', 'salamura'],
    summary: 'Turuncu rengi ve kesildiğinde salgıladığı havuç renkli sütüyle bilinen, çam ormanlarının sevilen sonbahar mantarı.',
    description: [
      'Kanlıca, kızılçam ve karaçam ormanlarında sonbahar yağmurlarıyla bol miktarda yetişir. Türkiye’de en çok toplanan ve tüketilen doğa mantarlarından biridir.',
      'Taze olarak hızla sevk edilir; ayrıca salamura olarak işlenerek uzun raf ömrü kazandırılır.',
    ],
    features: [
      ['Şapka', '4–14 cm, ortası çukur, halkalı turuncu desen'],
      ['Süt', 'Kesildiğinde turuncu süt salgılar, zamanla yeşillenir'],
      ['Alt yüzey', 'Sık, turuncu lameller'],
      ['Sınıflandırma', 'Boy ve şapka bütünlüğüne göre'],
    ],
    usage: 'Izgara, közleme, tereyağında kavurma, turşu.',
  },
  {
    slug: 'borazan-mantari',
    name: 'Borazan Mantarı',
    latin: 'Craterellus cornucopioides',
    trade: 'Black Trumpet',
    otherNames: ['Siyah borazan'],
    shape: 'trumpet',
    color: '#3A3433',
    season: [8, 9, 10, 11],
    regions: ['Karadeniz', 'Marmara'],
    forms: ['kurutulmus', 'taze'],
    summary: 'Koyu rengi ve derin, dumanlı aromasıyla gurme mutfakların aradığı, kurutmaya çok uygun bir tür.',
    description: [
      'Borazan mantarı nemli kayın ve meşe ormanlarında, yaprak örtüsü altında gruplar halinde yetişir. Koyu rengi nedeniyle toplanması deneyim ister.',
      'İnce etli yapısı sayesinde hızlı ve dengeli kurur; kuruduğunda aroması daha da yoğunlaşır.',
    ],
    features: [
      ['Şapka', 'Boru – huni biçimli, 3–8 cm'],
      ['Renk', 'Koyu gri – siyah'],
      ['Et', 'İnce, esnek'],
      ['Koku', 'Toprak ve hafif dumanlı'],
    ],
    usage: 'Soslar, risotto, balık yemekleri; toz haline getirilerek baharat olarak.',
  },
  {
    slug: 'kirpi-mantari',
    name: 'Kirpi Mantarı',
    latin: 'Hydnum repandum',
    trade: 'Hedgehog Mushroom',
    otherNames: ['Sarı dikenli mantar'],
    shape: 'spiny',
    color: '#E4B98A',
    season: [8, 9, 10, 11],
    regions: ['Karadeniz', 'Marmara'],
    forms: ['taze', 'dondurulmus'],
    summary: 'Şapkasının altındaki diken benzeri çıkıntılarıyla kolay tanınan, sıkı etli ve hafif tatlı bir orman mantarı.',
    description: [
      'Kirpi mantarı yaprak döken ve iğne yapraklı karışık ormanlarda yetişir. Lameller yerine diken benzeri yapılara sahip olması onu diğer türlerden ayırır.',
      'Sıkı yapısı taşımaya dayanıklıdır; taze ve dondurulmuş olarak hazırlanır.',
    ],
    features: [
      ['Şapka', '4–15 cm, krem – somon rengi'],
      ['Alt yüzey', 'Kısa, kırılgan dikenler'],
      ['Et', 'Beyaz, sıkı'],
      ['Tat', 'Tatlımsı, hafif fındıksı'],
    ],
    usage: 'Sote, güveç, makarna ve et yemekleri.',
  },
  {
    slug: 'yaz-trufu',
    name: 'Yaz Trüfü',
    latin: 'Tuber aestivum',
    trade: 'Summer Truffle',
    otherNames: ['Domalan'],
    shape: 'truffle',
    color: '#2E2622',
    season: [5, 6, 7, 8],
    regions: ['Ege', 'Marmara', 'İç Anadolu', 'Karadeniz'],
    forms: ['taze'],
    summary: 'Toprak altında gelişen, eşsiz aromasıyla “mutfağın elması” sayılan trüf ailesinin yaz türü.',
    description: [
      'Yaz trüfü meşe, fındık ve kayın gibi ağaçların kökleriyle ortak yaşar ve toprağın 5–20 cm altında gelişir. Eğitimli köpeklerle aranarak toplanır.',
      'Toplanan trüfler fırçalanarak temizlenir, ağırlık ve bütünlüğe göre sınıflandırılır ve aroma kaybı olmaması için en kısa sürede sevk edilir.',
    ],
    features: [
      ['Görünüm', 'Siyah, piramidal siğilli yüzey'],
      ['İç yapı', 'Açık kahve, beyaz damarlı'],
      ['Ağırlık', 'Genellikle 20–200 g'],
      ['Aroma', 'Fındık ve toprak notaları'],
    ],
    usage: 'Taze rendelenerek makarna, yumurta, risotto ve carpaccio üzerinde.',
  },
];
